# Generated by Django 3.1.7 on 2021-03-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_name", models.CharField(db_index=True, max_length=255)),
                ("build_number", models.PositiveIntegerField()),
                ("submitted", models.DateTimeField()),
                ("completed", models.DateTimeField(null=True)),
                ("task_id", models.UUIDField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="build",
            constraint=models.UniqueConstraint(
                fields=("build_name", "build_number"), name="unique_build"
            ),
        ),
    ]
