# Generated by Django 4.0.2 on 2022-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gentoo_build_publisher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildmodel",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
