# Generated by Django 3.2.2 on 2021-05-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0003_auto_20210506_1520"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeptBuild",
            fields=[
                (
                    "build_model",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gentoo_build_publisher.buildmodel",
                    ),
                ),
            ],
        ),
    ]
