# Generated by Django 3.2.2 on 2021-05-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0005_copy_keep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildmodel",
            name="keep",
        ),
    ]
