# Generated by Django 3.2.3 on 2021-06-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0007_addnotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logs", models.TextField()),
                (
                    "build_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gentoo_build_publisher.buildmodel",
                    ),
                ),
            ],
        ),
    ]
