# Generated by Django 3.2.9 on 2021-11-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0008_buildlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildmodel",
            name="task_id",
        ),
    ]
