# Generated by Django 4.0.2 on 2022-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0009_remove_buildmodel_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildmodel",
            name="built",
            field=models.DateTimeField(null=True),
        ),
    ]
