# Generated by Django 4.0.2 on 2022-02-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gentoo_build_publisher", "0010_build_model_add_built"),
    ]

    operations = [migrations.RenameField("BuildModel", "name", "machine")]
