[project]
name = "gentoo-build-publisher"
dynamic = ["version"]
description = "Gentoo Build Publisher"
authors = [{name = "Albert Hopkins", email = "marduk@letterboxes.org"}]
dependencies = [
    "ariadne>=0.14.0",
    "ariadne_django",
    "celery[msgpack]",
    "dataclasses-json",
    "django",
    "pydantic",
    "python-dateutil",
    "python-dispatch>=0.2.0",
    "requests",
    "simplejson",
    "yarl",
]

[project.urls]
homepage = "https://github.com/enku/gentoo-build-publisher"
repository = "https://github.com/enku/gentoo-build-publisher"

[project.entry-points."gentoo_build_publisher.records"]
django = "gentoo_build_publisher.models:RecordDB"

[build-system]
requires = [
    "setuptools>45",
    "setuptools_scm>=6.2",
    "wheel"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.coverage.run]
source = ["gentoo_build_publisher"]
omit = ["src/gentoo_build_publisher/migrations/*"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
load-plugins = "pylint_django"
django-settings-module = "settings"
init-hook = "import sys; sys.path.insert(0, 'tests')"
ignore = ["/migrations/"]

[tool.flake8]
max-line-length = 88

[tool.mypy]
plugins =["mypy_django_plugin.main"]
exclude = ["/migrations/"]
files = ["src/gentoo_build_publisher"]
mypy_path = ["tests", "stubs"]
strict = true

[[tool.mypy.overrides]]
module = "gentoo_build_publisher.admin"
ignore_errors = true

[[tool.mypy.overrides]]
module = "ariadne_django.*"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "settings"
