[build-system]
requires = [
    "setuptools>45",
    "setuptools_scm>=6.2",
    "wheel"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.coverage.run]
source = ["gentoo_build_publisher"]
omit = ["src/gentoo_build_publisher/migrations/*"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
load-plugins = "pylint_django"
django-settings-module = "settings"
init-hook = "import sys; sys.path.insert(0, 'tests')"
ignore = ["/migrations/"]
