pipeline {
    agent any

    environment {
        machine = "${env.JOB_BASE_NAME}"
        build = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('sync repos') {
            steps {
                script {
                    def fileName = "${env.JOB_BASE_NAME}/repos"
                    def repos = readFile(file: fileName).split("\n")
                    for (String repo: repos) {
                        copyArtifacts(projectName: "repos/${repo}")
                    }
                }
            }
        }
        stage('build chroot') {
            steps {
                sh 'make chroot'
            }
        }
        stage('update world') {
            steps {
                sh 'make world'
            }
        }
        stage('build artifacts') {
            steps {
                sh 'make archive'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'build.tar.gz'
            sh 'make push'
        }
        failure {
            sh 'make logs.tar.gz emerge-info.txt'
            emailext to: "${env.GBP_FAILURES_EMAIL}",
            subject: "${env.JOB_BASE_NAME} #${env.BUILD_NUMBER} failed",
            body: "See ${env.BUILD_URL} for the deets",
            attachmentsPattern: 'logs.tar.gz, emerge-info.txt',
            attachLog: true
        }
    }
}
